# The `meta`, `result` and `feedback` fields are reserved for the standard
# and must always be present.

std_skills/Meta meta
string scan_id
int8 face_id
---
std_skills/Result result
---
std_skills/Feedback feedback



